repositories:
  remote:
   - https://repo.maven.apache.org/maven2

artifacts:
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.1.1
  javaee_api: javax:javaee-api:jar:8.0
  javax_javaee_endorsed: javax:javaee-endorsed-api:jar:7.0

  geolatte_geom: org.geolatte:geolatte-geom:jar:1.0.1
  jts: com.vividsolutions:jts:jar:1.13
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.5.1
  postgresql: org.postgresql:postgresql:jar:42.2.11
  postgis_jdbc: net.postgis:postgis-jdbc:jar:2.5.0
  postgis_geometry: net.postgis:postgis-geometry:jar:2.5.0

  jtds: net.sourceforge.jtds:jtds:jar:1.3.1
