repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  javaee_api: javax:javaee-api:jar:7.0
  javax_javaee_endorsed: javax:javaee-endorsed-api:jar:7.0

  geolatte_geom: org.geolatte:geolatte-geom:jar:1.0.1
  jts: com.vividsolutions:jts:jar:1.13
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.5.1
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  postgis_jdbc: org.postgis:postgis-jdbc:jar:1.3.3
  jtds: net.sourceforge.jtds:jtds:jar:1.3.1
