repositories:
  remote:
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9

  geolatte_geom: org.geolatte:geolatte-geom:jar:0.12
  jts: com.vividsolutions:jts:jar:1.13
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6

  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  eclipselink: org.eclipse.persistence:eclipselink:jar:2.3.0
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  postgis_jdbc: org.postgis:postgis-jdbc:jar:1.3.3
  jtds: net.sourceforge.jtds:jtds:jar:1.2.7
